[vitejs]
src.github_tag = "vitejs/vite"
src.exclude_regex = ".*(alpha|beta|@).*"
fetch.github = "vitejs/vite"

[fcitx5-pinyin-zenith]
src.github = "ZenQy/scel2dict"
fetch.url = "https://github.com/ZenQy/scel2dict/releases/download/$ver/zenith.dict"

[wallpapers]
src.github = "ZenQy/wallpaper"
fetch.url = "https://github.com/ZenQy/wallpaper/releases/download/$ver/wallpaper.tar.gz"

[Ech0]
src.github = "lin-snow/Ech0"
fetch.github = "lin-snow/Ech0"

[Ech0-frontend]
src.github = "lin-snow/Ech0"
fetch.github = "lin-snow/Ech0"

[linux-flippy-612]
src.git = "https://github.com/unifreq/linux-6.12.y"
fetch.github = "unifreq/linux-6.12.y"
extract = ["Makefile"]

[linux-flippy-618]
src.github_tag = "unifreq/linux-6.18.y"
fetch.github = "unifreq/linux-6.18.y"

[einat]
src.github = "EHfive/einat-ebpf"
fetch.github = "EHfive/einat-ebpf"
extract = ["Cargo.lock"]
